name: Backend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'clarifi-api/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'clarifi-api/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clarifi-api

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: clarifi-api/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linters
      run: npm run lint

    - name: Run tests
      run: npm run test # Assumes a test script exists in clarifi-api/package.json

    - name: Build application
      run: npm run build 