name: Frontend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'clarifi-mobile/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'clarifi-mobile/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clarifi-mobile

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: clarifi-mobile/package-lock.json # Assuming package-lock.json exists for caching

    - name: Install dependencies
      run: npm ci

    - name: Run linters
      run: npm run lint # Assumes a lint script exists in clarifi-mobile/package.json

    # Optional: Add a build step if applicable (e.g., for web export check)
    # - name: Build for Web (optional check)
    #   run: npx expo export:web 